# Generated by Django 3.2.15 on 2022-09-27 16:41

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20220926_2247'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='author_user_unique',
        ),
        migrations.RemoveConstraint(
            model_name='follow',
            name='author_not_user',
        ),
        migrations.RenameField(
            model_name='follow',
            old_name='author',
            new_name='following',
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.UniqueConstraint(fields=('following', 'user'), name='following_user_unique'),
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.CheckConstraint(check=models.Q(('following', django.db.models.expressions.F('user')), _negated=True), name='following_not_user'),
        ),
    ]
